# Generated by Django 4.0.4 on 2022-05-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_blogmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
                ('birthdate', models.DateField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
