# Generated by Django 4.0.4 on 2022-05-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_blogusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogusers',
            name='email',
            field=models.EmailField(default='NULL', max_length=40),
        ),
    ]
