# Generated by Django 4.0.4 on 2022-05-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_alter_blogmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='image',
        ),
    ]
